using System;
using MongoDB.Bson.Serialization.Attributes;

namespace Atheer.Models
{
    // Because _id is generated by MongoDB and here there is not _id property
    [BsonIgnoreExtraElements]
    public class UserLoginAttempt
    {
        public string UserId { get; set; }
        public DateTime AttemptAt { get; set; }
        public bool SuccessfulLogin { get; set; }
    }
}